# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQ6XNDsoS3r6_GbPb9bfTA8qqPFGVfm6
"""

class Estudiante:
    """
    Clase estudiante que permite crear objetos de tipo estudiante.
    """

    def __init__(self, nombre, cedula, semestre):
        self.__nombre = nombre
        self.__cedula = cedula
        self.__semestre = semestre

    # GETTERS
    @property
    def nombre(self):
        return self.__nombre

    @property
    def cedula(self):
        return self.__cedula

    @property
    def semestre(self):
        return self.__semestre

    # SETTERS
    @nombre.setter
    def nombre(self, nuevo_nombre):
        self.__nombre = nuevo_nombre

    @cedula.setter
    def cedula(self, nueva_cedula):
        self.__cedula = nueva_cedula

    @semestre.setter
    def semestre(self, nuevo_semestre):
        self.__semestre = nuevo_semestre

    def __str__(self):
        return f'Estudiante [nombre: {self.__nombre}, cedula: {self.__cedula}, semestre: {self.__semestre}]'


# PRUEBA
if __name__ == '__main__':
    estudiante1 = Estudiante('Juan', '1234567890', '3er semestre')

    print(estudiante1)

    # Usando propiedades (forma correcta)
    print(estudiante1.nombre)
    print(estudiante1.cedula)
    print(estudiante1.semestre)